Create UserController and add dependencies to build.gradle
piotr-grosicki/project-jdp-2104-2 pull request #1
Opened 2021-05-03 16:19 UTC by ZadrogaB

Create endpoints to UserController (without exceptions right now). Add lombok and mysql connector to build.gradle.

2021-05-04 08:31 UTC, piotr-grosicki requested changes

2021-05-04 08:31 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    //PLACE FOR PARAMETERS
nie zostawiamy takich komentarzy w kodzie, powoduje to niepotrzebny balagan

2021-05-04 08:31 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    public void createUser(/*@RequestBody userDto userDto*/) {
dlaczego zakomentowane? nie bedzie sie dalo przetestowac takiego controllera

2021-05-04 08:31 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    public void blockUser(@RequestParam int userId) {
id to longi

2021-05-04 08:31 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    public int generateKey(@RequestParam int userId) {
id to longi

2021-05-04 10:47 UTC, ZadrogaB commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    public void createUser(/*@RequestBody userDto userDto*/) {
Myślałem, że na razie mamy nie tworzyć Dto. Stworzę wydmuszkę userDto, odkomentuję i wrzucę poprawki.

2021-05-04 10:48 UTC, ZadrogaB commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    public void blockUser(@RequestParam int userId) {
W schemacie mieliśmy je oznaczone jako int i chciałem się tego trzymać, zaraz zmieniam.

2021-05-04 12:03 UTC, piotr-grosicki requested changes

2021-05-04 12:03 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +@RequestMapping("/group_project/user")
ten endpoint `group_project` zostal uzdgodniony z grupa?  zwyczajowo uzywa sie `v1`

2021-05-04 12:03 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    public void createUser(@RequestBody userDto userDto) {
userDto jest puste, jak przetestujemy to? :)

2021-05-05 08:53 UTC, piotr-grosicki approved these changes

2021-05-05 08:53 UTC, merged