Create Order entity, moved Order and User from domain to entities package
piotr-grosicki/project-jdp-2104-2 pull request #10
Opened 2021-05-06 15:54 UTC by ZadrogaB

2021-05-06 15:56 UTC, ZadrogaB commented
Encję Order i User przeniosłem z domain do entities żeby nie było dwóch folderów z taką samą zawartością

2021-05-06 16:20 UTC, ZadrogaB commented
Ostatecznie zmiana nazwy folderu z encjami na domain

2021-05-07 07:54 UTC, piotr-grosicki requested changes

2021-05-07 07:54 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    @Column(name = "status")
mapowanie enumow troszke inaczej wyglada: https://www.baeldung.com/jpa-persisting-enums-in-jpa

2021-05-07 12:47 UTC, merged