JDP210402-12
piotr-grosicki/project-jdp-2104-2 pull request #12
Opened 2021-05-06 19:41 UTC by gralusek

2021-05-07 07:56 UTC, piotr-grosicki requested changes
konflikty

2021-05-07 16:55 UTC, gralusek commented
Konflikty rozwiązane

2021-05-07 17:04 UTC, piotr-grosicki requested changes
uporzadkowac idki w encjach

2021-05-10 06:54 UTC, piotr-grosicki requested changes

2021-05-10 06:54 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +    public OrderDto deleteOrder(@RequestParam OrderDto Id) {
`long id`

2021-05-10 06:54 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +    public OrderDto getOrder(@RequestParam OrderDto Id) {
`long id`

2021-05-12 09:26 UTC, piotr-grosicki approved these changes

2021-05-12 09:26 UTC, merged