Jdp210402 25
piotr-grosicki/project-jdp-2104-2 pull request #22
Opened 2021-05-12 21:11 UTC by ZadrogaB

2021-05-12 21:14 UTC, ZadrogaB commented
Testy zmienione w porozumieniu z Kamilem

2021-05-13 19:17 UTC, gralusek requested changes

2021-05-13 19:17 UTC, gralusek commented on src/main/java/com/kodilla/ecommercee/UserController.java
>          return key;
Generujesz key, ale powinien on chyba też zostać jakoś przypisany do usera?

2021-05-13 19:17 UTC, gralusek commented on src/main/java/com/kodilla/ecommercee/UserController.java
>      }
brakuje mi tu "keyValidDate". Pole to jest w encji Usera, ale oprócz tego, że jest generowane przez generateKey() to nie jest zapisywana do obiektu User. Moim zdaniem trzeba by to jakoś dodać

2021-05-13 19:17 UTC, gralusek commented on src/main/java/com/kodilla/ecommercee/dbServices/UserDbService.java
>      }
z tego w sumie też nie korzystamy

2021-05-13 19:17 UTC, gralusek commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +@Entity(name = "`Groups`")
Po co tutaj te znaki "  ` "?

2021-05-14 09:05 UTC, KamilGimpZAC commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +@Entity(name = "`Groups`")
MySQL ma słowa zarezerwowane i bez tych znaków controller nie zadziała bo baza danych nie przeczyta tego jako nazwy tabeli tylko nazwę operacji

2021-05-14 10:37 UTC, ZadrogaB commented on src/main/java/com/kodilla/ecommercee/Dto/UserDto.java
> +    private List<Order> orders;
Fakt, zaraz poprawię dopóki komputera nie odpiąłem

2021-05-14 10:42 UTC, ZadrogaB commented on src/main/java/com/kodilla/ecommercee/UserController.java
>          return key;
W metodzie generateKey() po wygenerowaniu klucza jest on zapisywany do pola userKey, tak samo keyValidDate jest w tej metodzie tworzony i zapisywany do pola obiektu user. Po `service.saveUser(user); ` jest on widoczny w bazie danych także wszystko działa

2021-05-14 10:54 UTC, ZadrogaB commented on src/main/java/com/kodilla/ecommercee/dbServices/UserDbService.java
>      }
Jest wykorzystywane w UserTestSuite do czyszczenie bazy między kolejnymi testami

2021-05-14 11:05 UTC, ZadrogaB commented on src/main/java/com/kodilla/ecommercee/UserController.java
>      }
W metodzie Usera generateKey() przypisuję polu keyValidDate i userKey wartości (4 i 5 linijka na dole) i są one już w tym momencie zapisane do obiektu, a następnie w endpointcie generateKey() po `service.saveUser(user);` są one zapisywane również do bazy danych. Z tego co zrozumiałem to po createUser nie mamy jeszcze tworzyć klucza, ale dopytam się jeszcze w sobotę na spotkaniu jak to ma wyglądać.

`public int generateKey() {
        int max = 999999999;
        int min = 100000000;
        keyValidDate = LocalDateTime.now().plusHours(1);
        userKey = (int) (Math.random() * ((max - min) + 1)) + min;
        return userKey;
    }`

2021-05-15 15:21 UTC, piotr-grosicki requested changes

2021-05-15 15:21 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +        int key = user.generateKey();
logika powinna byc wyciagnieta do serwisu

2021-05-19 10:48 UTC, piotr-grosicki approved these changes

2021-05-19 16:49 UTC, merged