created GroupController endpoints
piotr-grosicki/project-jdp-2104-2 pull request #23
Opened 2021-05-13 01:56 UTC by Wieszczycki

2021-05-13 07:26 UTC, ZadrogaB requested changes

2021-05-13 07:26 UTC, ZadrogaB commented on src/main/java/com/kodilla/ecommercee/GroupController.java
> +        return new ArrayList<>();
Zmieniłbym `@RequestMapping(method = RequestMethod.GET` na `@GetMapping` żeby trzymać się jednego schematu w klasie i projekcie. 
Najpierw powinien być stworzony obiekt z ArrayListą, a potem dopiero zwracany tak jak tutaj: https://github.com/piotr-grosicki/project-jdp-2104-2/blob/JDP210402-1/src/main/java/com/kodilla/ecommercee/OrderController.java ). Wcześniej był to problem więc podejrzewam, że tutaj też trzeba to poprawić

2021-05-13 07:26 UTC, ZadrogaB commented on src/main/java/com/kodilla/ecommercee/GroupController.java
> +    public GroupDto getGroup(Long groupId) {
Brak '@RequestParam'

2021-05-13 07:26 UTC, ZadrogaB commented on src/main/java/com/kodilla/ecommercee/GroupController.java
> +            @Override
Te wszystkie nadpisane metody chyba nie są potrzebne

2021-05-13 07:26 UTC, ZadrogaB commented on src/main/java/com/kodilla/ecommercee/GroupController.java
> +    public void deleteGroup(Long groupId) {
Brak '@RequestParam'

2021-05-13 07:26 UTC, ZadrogaB commented on src/main/java/com/kodilla/ecommercee/GroupController.java
> +    public GroupDto updateGroup(GroupDto groupDto) {
Brak `@RequestBody`

2021-05-13 07:26 UTC, ZadrogaB commented on src/main/java/com/kodilla/ecommercee/GroupController.java
> +            public int size() {
jw, metody nadpisane niepotrzebne

2021-05-13 07:26 UTC, ZadrogaB commented on src/main/java/com/kodilla/ecommercee/GroupController.java
> +    }
Brak `@RequestBody` i `@PostMapping`

2021-05-13 07:26 UTC, ZadrogaB commented on src/main/java/com/kodilla/ecommercee/GroupController.java
> +@RequestMapping("/v1/group/")
Wydaje mi się, że ukośnik na końcu `@RequestMapping` jest niepotrzebny

2021-05-13 07:26 UTC, ZadrogaB commented on src/main/java/com/kodilla/ecommercee/GroupController.java
> +        return new GroupDto(1L, "test group name", new List<ProductDto>() {
Wydaje mi się, że zamiast `new List<ProductDto>() ` powinna być `new ArrayList<>()` lub `new LinkedList<>()` bo inaczej nie pójdzie

2021-05-15 08:30 UTC, gralusek commented
Zrób update do maina i będzie git :)

2021-05-16 19:40 UTC, gralusek requested changes

2021-05-16 19:40 UTC, gralusek commented on src/main/java/com/kodilla/ecommercee/GroupController.java
> +    }
Tutaj powinno być `@RequestBody`, a nie Param

2021-05-18 00:02 UTC, Wieszczycki commented on src/main/java/com/kodilla/ecommercee/GroupController.java
> +    }
poprawione

2021-05-18 05:08 UTC, gralusek approved these changes

2021-05-18 22:15 UTC, ZadrogaB approved these changes

2021-05-18 22:35 UTC, merged