Jdp210402 24
piotr-grosicki/project-jdp-2104-2 pull request #25
Opened 2021-05-15 08:50 UTC by gralusek

2021-05-16 19:31 UTC, gralusek commented
W treści zdania jest, aby napisać nowe testy jeśli zmodyfikowałem repozytorium - w repo zrobiłem 4x Override, ale tylko 1 jest czymś nowym w porównaniu do testów CRUD, dlatego napisałem tylko 1 nowy test.

2021-05-17 13:00 UTC, piotr-grosicki commented
> W treści zdania jest, aby napisać nowe testy jeśli zmodyfikowałem repozytorium - w repo zrobiłem 4x Override, ale tylko 1 jest czymś nowym w porównaniu do testów CRUD, dlatego napisałem tylko 1 nowy test.

a w jakim celu zrobiles 4x override? w repozytoriach zwykle wpisuje sie tylko nowe metody, ktorych interfejs ze springa nie dostarcza lub jak chcemy zmienic jakis typ zwracany. wszystkie inne metody powinny dzialac bez nadpisywania

2021-05-17 17:36 UTC, gralusek commented
> 
> 
> > W treści zdania jest, aby napisać nowe testy jeśli zmodyfikowałem repozytorium - w repo zrobiłem 4x Override, ale tylko 1 jest czymś nowym w porównaniu do testów CRUD, dlatego napisałem tylko 1 nowy test.
> 
> a w jakim celu zrobiles 4x override? w repozytoriach zwykle wpisuje sie tylko nowe metody, ktorych interfejs ze springa nie dostarcza lub jak chcemy zmienic jakis typ zwracany. wszystkie inne metody powinny dzialac bez nadpisywania

Ok, w sumie wystarczy tylko 1 nadpisanie :D W find All zmieniłem typ z Iterable na List

2021-05-19 18:51 UTC, KamilGimpZAC requested changes

2021-05-19 18:51 UTC, KamilGimpZAC commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +        return orderMapper.mapToOrderDto(updatedOrder);
Wydaje mi się że trzeba usunąć poprzednią wersję Order z bazy danych

2021-05-19 18:51 UTC, KamilGimpZAC commented on src/main/java/com/kodilla/ecommercee/mapper/CartMapper.java
> +                .collect(Collectors.toList());
mappowanie można skrócić do this::mapToSth w celu ujednolicenia z mainem

2021-05-19 18:51 UTC, KamilGimpZAC commented on src/main/java/com/kodilla/ecommercee/mapper/CartMapper.java
> +                .collect(Collectors.toList());
j.w.

2021-05-19 18:51 UTC, KamilGimpZAC commented on src/main/java/com/kodilla/ecommercee/mapper/OrderMapper.java
> +                .collect(Collectors.toList());
j.w.

2021-05-19 18:51 UTC, KamilGimpZAC commented on src/main/java/com/kodilla/ecommercee/mapper/OrderMapper.java
> +                .collect(Collectors.toList());
j.w.

2021-05-19 18:51 UTC, KamilGimpZAC commented on src/main/java/com/kodilla/ecommercee/service/OrderService.java
> +        this.repository = repository;
ustalaliśmy że będziemy korzystać z lombocka więc zamiast pisać konstruktor można użyć adnotacji @RequiredArgsConstructor

2021-05-20 18:13 UTC, KamilGimpZAC approved these changes

2021-05-20 18:18 UTC, ZadrogaB approved these changes

2021-05-20 18:18 UTC, merged