JDP210402-23
piotr-grosicki/project-jdp-2104-2 pull request #26
Opened 2021-05-18 15:14 UTC by KamilGimpZAC

2021-05-18 18:58 UTC, gralusek requested changes

2021-05-18 18:58 UTC, gralusek commented on src/main/java/com/kodilla/ecommercee/CartController.java
>      }
W treści zadaniu (na kodilli) jest, że ma to być endpoint: utworzenie zamówienia na podstawie koszyka
Wydaje mi się, że powinieneś przekazać CartDto,

2021-05-19 10:46 UTC, KamilGimpZAC commented on src/main/java/com/kodilla/ecommercee/CartController.java
>      }
w OrderDto masz pole CartDto

2021-05-19 16:49 UTC, gralusek approved these changes

2021-05-19 18:36 UTC, merged