pierwsza implementacja GroupController, GroupRepository, GroupMapper
piotr-grosicki/project-jdp-2104-2 pull request #27
Opened 2021-05-20 01:16 UTC by Wieszczycki

Działają: getGroups, getGroup, deleteGroup, ale na razie nie wiem dlaczego nie działa CreateGroup (wywala NULL).

2021-05-20 11:14 UTC, KamilGimpZAC requested changes

2021-05-20 11:14 UTC, KamilGimpZAC commented on src/main/java/com/kodilla/ecommercee/GroupController.java
>          return new GroupDto(1L, "Edited group name", new ArrayList<>());
brakuje implementacji

2021-05-20 11:14 UTC, KamilGimpZAC commented on src/main/java/com/kodilla/ecommercee/dbServices/GroupDbService.java
> +    //public Group updateGroup(final Group group){ return GroupRepository.save(group);}
nie ma potrzeby pisać metody do update'u Groupy ponieważ tym zajmuje się controller

2021-05-20 11:14 UTC, KamilGimpZAC commented on src/main/java/com/kodilla/ecommercee/repositories/GroupRepository.java
> +    Optional<Group> findById(Long id);
nie ma potrzeby nadpisywania tej metody

2021-05-21 10:58 UTC, Wieszczycki commented on src/main/java/com/kodilla/ecommercee/GroupController.java
>          return new GroupDto(1L, "Edited group name", new ArrayList<>());
dodałem implementację

2021-05-21 10:59 UTC, Wieszczycki commented on src/main/java/com/kodilla/ecommercee/repositories/GroupRepository.java
> +    Optional<Group> findById(Long id);
usunąłem

2021-05-21 17:05 UTC, KamilGimpZAC commented on src/main/java/com/kodilla/ecommercee/dbServices/GroupDbService.java
> +                .orElseThrow(() -> new GroupNotExist());
Logika tej metody powinna znajdować się w controllerze

2021-05-21 20:35 UTC, Wieszczycki reviewed
uwzględnione poprawki od @KamilGimpZAC

2021-05-21 20:35 UTC, Wieszczycki commented on src/main/java/com/kodilla/ecommercee/dbServices/GroupDbService.java
> +                .orElseThrow(() -> new GroupNotExist());
Przeniesione do Controllera, i usunięta metoda updateGroup z GroupDbService

2021-05-21 20:37 UTC, KamilGimpZAC approved these changes

2021-05-21 20:42 UTC, merged