changes in ProductController&Product
piotr-grosicki/project-jdp-2104-2 pull request #5
Opened 2021-05-05 15:08 UTC by SandraOwczarek

2021-05-05 15:18 UTC, piotr-grosicki requested changes

2021-05-05 15:18 UTC, piotr-grosicki commented on build.gradle
> +    implementation 'org.projectlombok:lombok:1.18.18'
ta zaleznosc juz znajduje sie na branchy main

2021-05-05 15:18 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +    public ProductDto getProduct(Long productId) {
brakuje `@RequestParam`

2021-05-05 15:18 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +    public void deleteProduct(Long productId) {
brakuje `@RequestParam`

2021-05-05 15:18 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +    public ProductDto updateProduct(ProductDto productDto) {
brakuje `@RequestBody`

2021-05-05 15:18 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +    public void createProduct(ProductDto productDto) {
brakuje `@RequestBody`

2021-05-06 06:41 UTC, piotr-grosicki requested changes
konflikty

2021-05-06 19:51 UTC, ZadrogaB commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +    public ProductDto updateProduct(@RequestBody ProductDto productDto) {
Wydaje mi się, że przy RequestBody powinien jeszcze być parametr "consumes" z wartością "MediaType.APPLICATION_JSON_VALUE" w `@RequestMapping`

2021-05-06 19:51 UTC, ZadrogaB commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +    public void createProduct(@RequestBody ProductDto productDto){
jw

2021-05-07 07:45 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +    public ProductDto updateProduct(@RequestBody ProductDto productDto) {
nie jest niezbedny, powinno dzialac bez

2021-05-07 07:45 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +    public void createProduct(@RequestBody ProductDto productDto){
j.w.

2021-05-08 17:13 UTC, gralusek commented
jest konflikt

2021-05-08 18:18 UTC, piotr-grosicki requested changes
nadal jest konflikt plus twoj branch dodaje np encje order i user, ktorych nie powinien. sprobuj rozwiazac, jezeli sie nie uda to najprosciej zaczac zadanie na nowo odbijajac sie od aktualnej branchy main (pamietaj o poprawnej nazwie nowej branchy, ta aktualna nie jest zgodna ze schematem)

2021-05-11 13:32 UTC, closed without merging