OrderController update
piotr-grosicki/project-jdp-2104-2 pull request #8
Opened 2021-05-05 17:49 UTC by gralusek

W wyniku rozbudowy OrderDto (potrzebne do wstępnej implementacji OrderController), jest bug w CartController

2021-05-06 06:43 UTC, piotr-grosicki requested changes
projekt sie nie kompiluje

2021-05-06 17:27 UTC, gralusek commented
Zrobiłem update w CartController, projekt się kompiluje

2021-05-06 19:44 UTC, ZadrogaB commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +    public OrderDto addOrder(@RequestBody OrderDto orderDto) {
Wydaje mi się, że przy RequestBody powinieneś dodać jeszcze parametr "consumes" z wartością MediaType.APPLICATION_JSON_VALUE

2021-05-06 19:45 UTC, ZadrogaB commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +    public OrderDto updateOrder(@RequestBody OrderDto orderDto) {
jw

2021-05-07 07:51 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +    public OrderDto addOrder(@RequestBody OrderDto orderDto) {
nie jest niezbedny, powinno dzialac bez :)

2021-05-07 07:51 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +    public OrderDto updateOrder(@RequestBody OrderDto orderDto) {
j.w.

2021-05-07 07:52 UTC, piotr-grosicki requested changes

2021-05-07 07:52 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +    public OrderDto getOrder(@RequestParam OrderDto orderId) {
tutaj powinno byc samo id a nie orderDto

2021-05-07 07:52 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +    public OrderDto deleteOrder(@RequestParam OrderDto orderId) {
tutaj powinno byc samo id a nie orderDto

2021-05-08 18:20 UTC, piotr-grosicki requested changes
nadal te same bledy, nic sie nie zmienilo. patrzylem na commity: najpierw poprawiles a potem wrociles ponownie do blednej wersji

2021-05-08 18:20 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +    public OrderDto getOrder(@RequestParam OrderDto orderId) {
nadal aktualne

2021-05-09 15:32 UTC, gralusek commented
Trochę się pogubiłem z pullowaniem z gita, temu tyle commitow :P Ale z tego co ja widzę, to w ostatnim (ea24ed3) zmieniłem OrderId na samo id - gdzie widzisz że nadal jest źle?

2021-05-10 06:52 UTC, piotr-grosicki commented
> Trochę się pogubiłem z pullowaniem z gita, temu tyle commitow :P Ale z tego co ja widzę, to w ostatnim ([ea24ed3](https://github.com/piotr-grosicki/project-jdp-2104-2/commit/ea24ed34b29f0d277d6e1403060e6bb53ec78c56)) zmieniłem OrderId na samo id - gdzie widzisz że nadal jest źle?

zmieniles tylko nazwe a nie typ obiektu przekazanego w parametrze, wiec jest teraz `OrderDto id` co nie ma sensu :) powinno byc `long id`

2021-05-10 20:00 UTC, merged